name: simplet_stop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  provider: ^6.1.5
  http: ^1.4.0
  intl: ^0.20.2
  google_fonts: ^6.3.0
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.12
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.4.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/translations/
    