// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ZgqLYq8lxKxWtl3A__KJgYu7U5rYRHk',
    appId: '1:384636101779:web:436c1d0aea54f26dfa1966',
    messagingSenderId: '384636101779',
    projectId: 'simplet-8d2b3',
    authDomain: 'simplet-8d2b3.firebaseapp.com',
    storageBucket: 'simplet-8d2b3.firebasestorage.app',
    measurementId: 'G-NDDD41743C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlYHAYYCGwt7iQ3eBGsHaoYxYcVVfxgcs',
    appId: '1:384636101779:android:c7e8d70723dbb84efa1966',
    messagingSenderId: '384636101779',
    projectId: 'simplet-8d2b3',
    storageBucket: 'simplet-8d2b3.firebasestorage.app',
  );
}
